config/routes.rb
Rails.application.routes.draw do
  resources :book_activities
  resources :books

  root 'book_activities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_activities
end

app/models/book_activity.rb
class BookActivity < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_activities_controller.rb
class BookActivitiesController < ApplicationController
  before_action :set_book_activity, only: [:show, :edit, :update, :destroy]

  # GET /book_activities
  # GET /book_activities.json
  def index
    @book_activities = BookActivity.all
  end

  # GET /book_activities/1
  # GET /book_activities/1.json
  def show
  end

  # GET /book_activities/new
  def new
    @book_activity = BookActivity.new
    @books = Book.all
  end

  # GET /book_activities/1/edit
  def edit
    @books = Book.all
  end

  # POST /book_activities
  # POST /book_activities.json
  def create
    @book_activity = BookActivity.new(book_activity_params)

    respond_to do |format|
      if @book_activity.save
        @book = Book.find(book_activity_params[:book_id])
        @book.status = book_activity_params[:activity]
        @book.save
        format.html { redirect_to @book_activity, notice: 'Book activity was successfully created.' }
        format.json { render :show, status: :created, location: @book_activity }
      else
        format.html { render :new }
        format.json { render json: @book_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_activities/1
  # PATCH/PUT /book_activities/1.json
  def update
    respond_to do |format|
      if @book_activity.update(book_activity_params)
        @book = Book.find(book_activity_params[:book_id])
        @book.status = book_activity_params[:activity]
        @book.save
        format.html { redirect_to @book_activity, notice: 'Book activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_activity }
      else
        format.html { render :edit }
        format.json { render json: @book_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_activities/1
  # DELETE /book_activities/1.json
  def destroy
    @book_activity.destroy
    respond_to do |format|
      format.html { redirect_to book_activities_url, notice: 'Book activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_activity
      @book_activity = BookActivity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_activity_params
      params.require(:book_activity).permit(:book_id, :date, :activity)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:sort]
      case params[:sort]
      when 'desc'
        @books = Book.all.order(title: 'desc')
      else
        @books = Book.all.order(title: 'asc')
      end
    else
      @books = Book.all.order(title: 'asc')
    end
    if !params[:status].blank?
      @books = @books.where(status: params[:status])
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_activities_helper.rb
module BookActivitiesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book_activities/_form.html.erb
<%= form_with(model: book_activity, local: true) do |form| %>
  <% if book_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_activity.errors.count, "error") %> prohibited this book_activity from being saved:</h2>

      <ul>
        <% book_activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.select :book_id, options_from_collection_for_select(@books, :id, :title) %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :activity %>
    <%= form.select :activity, options_for_select([["Presté el libro", "prestado"], ["Devolvieron el libro", "estante"]], book_activity.activity) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_activities/edit.html.erb
<h1>Editing Book Activity</h1>

<%= render 'form', book_activity: @book_activity %>

<%= link_to 'Show', @book_activity %> |
<%= link_to 'Back', book_activities_path %>

app/views/book_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Activities</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Date</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_activities.each do |book_activity| %>
      <tr>
        <td><%= book_activity.book.title %></td>
        <td><%= book_activity.date %></td>
        <td><%= book_activity.activity === 'prestado' ? 'Prestado' : 'En estante' %></td>
        <td><%= link_to 'Show', book_activity %></td>
        <td><%= link_to 'Destroy', book_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Activity', new_book_activity_path %>

app/views/book_activities/new.html.erb
<h1>New Book Activity</h1>

<%= render 'form', book_activity: @book_activity %>

<%= link_to 'Back', book_activities_path %>

app/views/book_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_activity.book.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @book_activity.date %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @book_activity.activity === 'prestado' ? 'Prestado' : 'En estante' %>
</p>

<%= link_to 'Back', book_activities_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select([["En estante", "estante"], ["Prestado", "prestado"]], book.status), prompt: "Elija uno" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>
        Title<br>
        <% if params[:sort] && params[:sort] === 'desc' %>
          <%= link_to "🔼", request.query_parameters.merge({sort: 'asc'}) %>
        <% else %>
          <%= link_to "🔽", request.query_parameters.merge({sort: 'desc'}) %>
        <% end %>
      </th>
      <th>Author</th>
      <th>
        Status<br>
        <%= select_tag 'status', options_for_select([["Todos", ""], ["En estante", "estante"], ["Prestado", "prestado"]], params[:status]) %>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status === 'prestado' ? 'Prestado' : 'En estante'%></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

<script>
  function updateUrlParameter(uri, key, value) {
    let i = uri.indexOf('#');
    let hash = i === -1 ? ''  : uri.substr(i);
    uri = i === -1 ? uri : uri.substr(0, i);

    let re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
    let separator = uri.indexOf('?') !== -1 ? "&" : "?";
    if (uri.match(re)) {
        uri = uri.replace(re, '$1' + key + "=" + value + '$2');
    } else {
        uri = uri + separator + key + "=" + value;
    }
    return uri + hash;
  }

  (function() {
    document.getElementById("status").addEventListener('change', function() {
      let selectValue = document.getElementById("status").value;
      Turbolinks.visit(updateUrlParameter(window.location.href, 'status', selectValue));
    }, false);
  })();
</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= book.status === 'prestado' ? 'Prestado' : 'En estante' %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplicacionTareaBiblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="text-align: right"><%= link_to "Libros", books_path %> | <%= link_to "Actividades", book_activities_path %></p>
    <%= yield %>
  </body>
</html>